/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_logger_jni_Logger */

#ifndef _Included_com_logger_jni_Logger
#define _Included_com_logger_jni_Logger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_logger_jni_Logger
 * Method:    AddThread
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_logger_jni_Logger_AddThread
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_logger_jni_Logger
 * Method:    Init
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_logger_jni_Logger_Init__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_logger_jni_Logger
 * Method:    Init
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_logger_jni_Logger_Init__Ljava_lang_String_2Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     com_logger_jni_Logger
 * Method:    Run
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_logger_jni_Logger_Run
  (JNIEnv *, jobject);

/*
 * Class:     com_logger_jni_Logger
 * Method:    Debug
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_logger_jni_Logger_Debug
  (JNIEnv *, jobject, jstring, jstring, jint, jstring);

/*
 * Class:     com_logger_jni_Logger
 * Method:    Info
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_logger_jni_Logger_Info
  (JNIEnv *, jobject, jstring, jstring, jint, jstring);

/*
 * Class:     com_logger_jni_Logger
 * Method:    Warn
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_logger_jni_Logger_Warn
  (JNIEnv *, jobject, jstring, jstring, jint, jstring);

/*
 * Class:     com_logger_jni_Logger
 * Method:    Error
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_logger_jni_Logger_Error
  (JNIEnv *, jobject, jstring, jstring, jint, jstring);

/*
 * Class:     com_logger_jni_Logger
 * Method:    Finish
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_logger_jni_Logger_Finish
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
